project_id      = ""                # Your existing GCP project ID
region          = "us-central1"     # Recommended region
zone            = "us-central1-a"
vpc_name        = ""                # The name of the VPC to create
subnet_name     = ""                # The name of the subnet to create
vm_name         = ""                # The name of the VM to create
vm_username     = ""                # The username for the VM
api_key         = ""                # API Key
profile_name    = ""                # Profile name
git_repo_url    = ""                # Ask me